Repository kubernauts/tk8, pull requests merged in 2018-09, with the labels that each got.

#42 Release/v0.4.1
  Makefile
  addons/rancher/master.yaml
  cmd/addon.go
  config.yaml.example
  internal/cluster/aws.go
  internal/cluster/common.go
  internal/cluster/init.go
  test/version_test.go
Labels: Ready for Release

#44 MODIFY | Addon | Rancher | change LB to NP
  addons/rancher/master.yaml
Labels: enhancement

#48 HOTFIX | loadbalancer config
  internal/cluster/aws.go
Labels: bug

#49 Add support for Zsh and Bash autocompletion
  README.md
  cmd/completion.go
  internal/cluster/aws.go
Labels: enhancement

#51 Add prompt for AWS credentials when none is found
  internal/cluster/awsConfig.go
  internal/cluster/common.go
  internal/templates/config.go
Labels: bug
